### ISSUE TITLE
向大佬问个思路，Electron程序的插件实现思路

### ISSUE THREAD

**Issue by dongasai** [umbrella22/umbrella22#1]
我想用Electron写个软件，但是不知道插件系统如何实现，想请教一下思路。

**Comment by umbrella22** [comment]
emmm，同类型的你可以参考UTOOLS，or直接走chrome拓展？emm这方面我倒是真的没有什么经验

**Comment by dongasai** [comment]
UTOOLS 的仓库地址是啥？为什么我感觉我见过，我用过，甚至我看过代码，但是就是找不到了呢？github搜都没搜到。

**Comment by umbrella22** [comment]
商业化就关了叭
